package com.igridin.desktop_calculator;

import java.awt.*;

/**
 * Created by Igor Gridin on 23.12.16.
 *
 * This code was automatically created by NetBeans GUI Form Editor
 * I just modified some fields, like class constructor, buttons initialization and etc.
 **/
abstract class IngCalcFrame extends FrameForm {

    // Creates new form IngCalcFrame

    public IngCalcFrame() {
        initComponents();
        setLocation(frameStartPoint);
        setAlwaysOnTop(true);
        setVisible(true);
        button0.requestFocus();
        isClassicForm = false;
        IngCalcOperations.bktCount = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    private void initComponents() {


        setTitle("Инженерный калькулятор");
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        gradientPanel.setBackground(new Color(33, 59, 104));

        textArea.setColumns(20);
        textArea.setFont(new Font("Arial", 0, 20)); // NOI18N
        textArea.setForeground(new Color(255, 255, 255));
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setText("0");
        textArea.setOpaque(false);
        textArea.setEnabled(false);

        textArea.setDragEnabled(false);
        textArea.setHighlighter(null);
        textArea.setOpaque(false);
        textArea.setDisabledTextColor(Color.WHITE);
        textArea.setEnabled(false);


        bktField.setEditable(false);
        bktField.setBackground(null);
        bktField.setFont(new Font("Arial", 0, 12)); // NOI18N
        bktField.setForeground(new Color(255, 255, 255));
        bktField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        bktField.setText("");
        bktField.setBorder(null);
        bktField.setDisabledTextColor(new Color(255, 255, 255));
        bktField.setDragEnabled(false);
        bktField.setEnabled(false);
        bktField.setHighlighter(null);
        bktField.setOpaque(false);
        bktField.setRequestFocusEnabled(false);

        javax.swing.GroupLayout gradientPanelLayout = new javax.swing.GroupLayout(gradientPanel);
        gradientPanel.setLayout(gradientPanelLayout);
        gradientPanelLayout.setHorizontalGroup(
                gradientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(gradientPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bktField, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))
        );
        gradientPanelLayout.setVerticalGroup(
                gradientPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradientPanelLayout.createSequentialGroup()
                                .addComponent(bktField, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textArea, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        digitsPanel.setBackground(new Color(127, 127, 127));

        button0.setBackground(new Color(225, 225, 225));
        button0.setFont(new Font("Arial", 0, 24)); // NOI18N
        button0.setText("0");
        button0.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        button0.setBorderPainted(false);
        button0.setFocusPainted(false);
        button0.setOpaque(true);
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttonzap.setBackground(new Color(225, 225, 225));
        buttonzap.setFont(new Font("Arial", 0, 24)); // NOI18N
        buttonzap.setText(",");
        buttonzap.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        buttonzap.setBorderPainted(false);
        buttonzap.setFocusPainted(false);
        buttonzap.setOpaque(true);
        buttonzap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonzapActionPerformed(evt);
            }
        });

        buttonC.setBackground(new Color(225, 225, 225));
        buttonC.setFont(new Font("Arial", 0, 24)); // NOI18N
        buttonC.setText("C");
        buttonC.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        buttonC.setBorderPainted(false);
        buttonC.setFocusPainted(false);
        buttonC.setOpaque(true);
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });

        buttonEquals.setBackground(new Color(255, 153, 0));
        buttonEquals.setFont(new Font("Arial", 1, 24)); // NOI18N
        buttonEquals.setForeground(new Color(255, 255, 255));
        buttonEquals.setText("=");
        buttonEquals.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        buttonEquals.setBorderPainted(false);
        buttonEquals.setFocusPainted(false);
        buttonEquals.setOpaque(true);
        buttonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEqualsActionPerformed(evt);
            }
        });

        button1.setBackground(new Color(225, 225, 225));
        button1.setFont(new Font("Arial", 0, 24)); // NOI18N
        button1.setText("1");
        button1.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        button1.setBorderPainted(false);
        button1.setFocusPainted(false);
        button1.setOpaque(true);
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setBackground(new Color(225, 225, 225));
        button2.setFont(new Font("Arial", 0, 24)); // NOI18N
        button2.setText("2");
        button2.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        button2.setBorderPainted(false);
        button2.setFocusPainted(false);
        button2.setOpaque(true);
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        button3.setBackground(new Color(225, 225, 225));
        button3.setFont(new Font("Arial", 0, 24)); // NOI18N
        button3.setText("3");
        button3.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        button3.setBorderPainted(false);
        button3.setFocusPainted(false);
        button3.setOpaque(true);
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });

        buttonAdd.setBackground(new Color(255, 153, 0));
        buttonAdd.setFont(new Font("Arial", 1, 24)); // NOI18N
        buttonAdd.setForeground(new Color(255, 255, 255));
        buttonAdd.setText("+");
        buttonAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        buttonAdd.setBorderPainted(false);
        buttonAdd.setFocusPainted(false);
        buttonAdd.setOpaque(true);
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        button4.setBackground(new Color(225, 225, 225));
        button4.setFont(new Font("Arial", 0, 24)); // NOI18N
        button4.setText("4");
        button4.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        button4.setBorderPainted(false);
        button4.setOpaque(true);
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });

        button5.setBackground(new Color(225, 225, 225));
        button5.setFont(new Font("Arial", 0, 24)); // NOI18N
        button5.setText("5");
        button5.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        button5.setBorderPainted(false);
        button5.setOpaque(true);
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });

        button6.setBackground(new Color(225, 225, 225));
        button6.setFont(new Font("Times New Roman", 0, 24)); // NOI18N
        button6.setText("6");
        button6.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        button6.setBorderPainted(false);
        button6.setOpaque(true);
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        buttonSub.setBackground(new Color(255, 153, 0));
        buttonSub.setFont(new Font("Arial", 1, 24)); // NOI18N
        buttonSub.setForeground(new Color(255, 255, 255));
        buttonSub.setText("–");
        buttonSub.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        buttonSub.setBorderPainted(false);
        buttonSub.setFocusPainted(false);
        buttonSub.setOpaque(true);
        buttonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubActionPerformed(evt);
            }
        });

        button7.setBackground(new Color(225, 225, 225));
        button7.setFont(new Font("Arial", 0, 24)); // NOI18N
        button7.setText("7");
        button7.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        button7.setBorderPainted(false);
        button7.setFocusPainted(false);
        button7.setOpaque(true);
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        button8.setBackground(new Color(225, 225, 225));
        button8.setFont(new Font("Arial", 0, 24)); // NOI18N
        button8.setText("8");
        button8.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        button8.setBorderPainted(false);
        button8.setFocusPainted(false);
        button8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        button8.setOpaque(true);
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setBackground(new Color(225, 225, 225));
        button9.setFont(new Font("Arial", 0, 24)); // NOI18N
        button9.setText("9");
        button9.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(153, 153, 153)));
        button9.setBorderPainted(false);
        button9.setFocusPainted(false);
        button9.setOpaque(true);
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        buttonMult.setBackground(new Color(255, 153, 0));
        buttonMult.setFont(new Font("Arial", 1, 24)); // NOI18N
        buttonMult.setForeground(new Color(255, 255, 255));
        buttonMult.setText("×");
        buttonMult.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(153, 153, 153)));
        buttonMult.setBorderPainted(false);
        buttonMult.setFocusPainted(false);
        buttonMult.setOpaque(true);
        buttonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMultActionPerformed(evt);
            }
        });

        buttonSw.setBackground(new Color(225, 225, 225));
        buttonSw.setFont(new Font("Arial", 0, 14)); // NOI18N
        buttonSw.setText("Стандартный");
        buttonSw.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        buttonSw.setBorderPainted(false);
        buttonSw.setFocusPainted(false);
        buttonSw.setOpaque(true);
        buttonSw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSwActionPerformed(evt);
            }
        });

        buttonInterest.setBackground(new Color(225, 225, 225));
        buttonInterest.setFont(new Font("Arial", 0, 20)); // NOI18N
        buttonInterest.setText("%");
        buttonInterest.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204, 204, 204)));
        buttonInterest.setBorderPainted(false);
        buttonInterest.setFocusPainted(false);
        buttonInterest.setOpaque(true);
        buttonInterest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInterestActionPerformed(evt);
            }
        });

        buttonDiv.setBackground(new Color(255, 153, 0));
        buttonDiv.setFont(new Font("Arial", 1, 24)); // NOI18N
        buttonDiv.setForeground(new Color(255, 255, 255));
        buttonDiv.setText("÷");
        buttonDiv.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonDiv.setBorderPainted(false);
        buttonDiv.setFocusPainted(false);
        buttonDiv.setOpaque(true);
        buttonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDivActionPerformed(evt);
            }
        });

        buttonBktOpen.setBackground(new Color(225, 225, 225));
        buttonBktOpen.setFont(new Font("Arial", 0, 24)); // NOI18N
        buttonBktOpen.setText("(");
        buttonBktOpen.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonBktOpen.setBorderPainted(false);
        buttonBktOpen.setFocusPainted(false);
        buttonBktOpen.setOpaque(true);
        buttonBktOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBktOpenActionPerformed(evt);
            }
        });

        buttonBktClose.setBackground(new Color(225, 225, 225));
        buttonBktClose.setFont(new Font("Arial", 0, 24)); // NOI18N
        buttonBktClose.setText(")");
        buttonBktClose.setToolTipText("");
        buttonBktClose.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonBktClose.setBorderPainted(false);
        buttonBktClose.setFocusPainted(false);
        buttonBktClose.setOpaque(true);
        buttonBktClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBktCloseActionPerformed(evt);
            }
        });

        buttonRoot.setBackground(new Color(204, 204, 204));
        buttonRoot.setFont(new Font("Arial", 0, 24)); // NOI18N
        buttonRoot.setText("√");
        buttonRoot.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonRoot.setBorderPainted(false);
        buttonRoot.setFocusPainted(false);
        buttonRoot.setOpaque(true);
        buttonRoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRootActionPerformed(evt);
            }
        });

        buttonDelete.setBackground(new Color(204, 0, 0));
        buttonDelete.setFont(new Font("Arial", 0, 24)); // NOI18N
        buttonDelete.setForeground(new Color(255, 255, 255));
        buttonDelete.setText("Del");
        buttonDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonDelete.setBorderPainted(false);
        buttonDelete.setFocusPainted(false);
        buttonDelete.setOpaque(true);
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        buttonPow.setBackground(new Color(204, 204, 204));
        buttonPow.setFont(new Font("Arial", 0, 24)); // NOI18N
        buttonPow.setText("x^");
        buttonPow.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonPow.setBorderPainted(false);
        buttonPow.setOpaque(true);
        buttonPow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPowActionPerformed(evt);
            }
        });

        buttonExp.setBackground(new Color(204, 204, 204));
        buttonExp.setFont(new Font("Arial", 0, 24)); // NOI18N
        buttonExp.setText("e^");
        buttonExp.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonExp.setBorderPainted(false);
        buttonExp.setFocusPainted(false);
        buttonExp.setOpaque(true);
        buttonExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExpActionPerformed(evt);
            }
        });

        buttonOneDivX.setBackground(new Color(204, 204, 204));
        buttonOneDivX.setFont(new Font("Arial", 0, 24)); // NOI18N
        buttonOneDivX.setText("1/x");
        buttonOneDivX.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonOneDivX.setBorderPainted(false);
        buttonOneDivX.setOpaque(true);
        buttonOneDivX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOneDivXActionPerformed(evt);
            }
        });

        separatorPanel.setBackground(new Color(255, 255, 255));

        javax.swing.GroupLayout separatorPanelLayout = new javax.swing.GroupLayout(separatorPanel);
        separatorPanel.setLayout(separatorPanelLayout);
        separatorPanelLayout.setHorizontalGroup(
                separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 2, Short.MAX_VALUE)
        );
        separatorPanelLayout.setVerticalGroup(
                separatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 239, Short.MAX_VALUE)
        );

        buttonMr.setBackground(new Color(0, 153, 153));
        buttonMr.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonMr.setForeground(new Color(255, 255, 255));
        buttonMr.setText("MR");
        buttonMr.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonMr.setBorderPainted(false);
        buttonMr.setFocusPainted(false);
        buttonMr.setOpaque(true);
        buttonMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMrActionPerformed(evt);
            }
        });

        buttonMc.setBackground(new Color(0, 153, 153));
        buttonMc.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonMc.setForeground(new Color(255, 255, 255));
        buttonMc.setText("MC");
        buttonMc.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonMc.setBorderPainted(false);
        buttonMc.setOpaque(true);
        buttonMc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMcActionPerformed(evt);
            }
        });

        buttonMPlus.setBackground(new Color(0, 204, 204));
        buttonMPlus.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonMPlus.setForeground(new Color(255, 255, 255));
        buttonMPlus.setText("M+");
        buttonMPlus.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonMPlus.setBorderPainted(false);
        buttonMPlus.setOpaque(true);
        buttonMPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMPlusActionPerformed(evt);
            }
        });

        buttonMMinus.setBackground(new Color(0, 204, 204));
        buttonMMinus.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonMMinus.setForeground(new Color(255, 255, 255));
        buttonMMinus.setText("M-");
        buttonMMinus.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonMMinus.setBorderPainted(false);
        buttonMMinus.setFocusPainted(false);
        buttonMMinus.setOpaque(true);
        buttonMMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMMinusActionPerformed(evt);
            }
        });

        buttonPi.setBackground(new Color(204, 204, 204));
        buttonPi.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonPi.setText("п");
        buttonPi.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonPi.setBorderPainted(false);
        buttonPi.setFocusPainted(false);
        buttonPi.setOpaque(true);
        buttonPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPiActionPerformed(evt);
            }
        });

        buttonLog.setBackground(new Color(204, 204, 204));
        buttonLog.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonLog.setText("lg");
        buttonLog.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonLog.setBorderPainted(false);
        buttonLog.setFocusPainted(false);
        buttonLog.setOpaque(true);
        buttonLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogActionPerformed(evt);
            }
        });

        buttonLn.setBackground(new Color(204, 204, 204));
        buttonLn.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonLn.setText("ln");
        buttonLn.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonLn.setBorderPainted(false);
        buttonLn.setFocusPainted(false);
        buttonLn.setOpaque(true);
        buttonLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLnActionPerformed(evt);
            }
        });

        buttonSin.setBackground(new Color(204, 204, 204));
        buttonSin.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonSin.setText("sin");
        buttonSin.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonSin.setBorderPainted(false);
        buttonSin.setFocusPainted(false);
        buttonSin.setOpaque(true);
        buttonSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSinActionPerformed(evt);
            }
        });

        buttonCos.setBackground(new Color(204, 204, 204));
        buttonCos.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonCos.setText("cos");
        buttonCos.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonCos.setBorderPainted(false);
        buttonCos.setFocusPainted(false);
        buttonCos.setOpaque(true);
        buttonCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCosActionPerformed(evt);
            }
        });

        buttonTg.setBackground(new Color(204, 204, 204));
        buttonTg.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonTg.setText("tg");
        buttonTg.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonTg.setBorderPainted(false);
        buttonTg.setFocusPainted(false);
        buttonTg.setOpaque(true);
        buttonTg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTgActionPerformed(evt);
            }
        });

        buttonAsin.setBackground(new Color(204, 204, 204));
        buttonAsin.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonAsin.setText("asin");
        buttonAsin.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonAsin.setBorderPainted(false);
        buttonAsin.setFocusPainted(false);
        buttonAsin.setOpaque(true);
        buttonAsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAsinActionPerformed(evt);
            }
        });

        buttonAcos.setBackground(new Color(204, 204, 204));
        buttonAcos.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonAcos.setText("acos");
        buttonAcos.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonAcos.setBorderPainted(false);
        buttonAcos.setFocusPainted(false);
        buttonAcos.setOpaque(true);
        buttonAcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcosActionPerformed(evt);
            }
        });

        buttonAtan.setBackground(new Color(204, 204, 204));
        buttonAtan.setFont(new Font("Arial", 0, 22)); // NOI18N
        buttonAtan.setText("atg");
        buttonAtan.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0, 0, 0)));
        buttonAtan.setBorderPainted(false);
        buttonAtan.setFocusPainted(false);
        buttonAtan.setOpaque(true);
        buttonAtan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAtanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout digitsPanelLayout = new javax.swing.GroupLayout(digitsPanel);
        digitsPanel.setLayout(digitsPanelLayout);
        digitsPanelLayout.setHorizontalGroup(
                digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                                .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(1, 1, 1)
                                                .addComponent(buttonzap, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(1, 1, 1)
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(buttonSw, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(buttonInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(buttonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(1, 1, 1)
                                                .addComponent(separatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(1, 1, 1)
                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(buttonSin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonPi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonAsin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(buttonBktOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(buttonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(buttonCos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonAcos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(1, 1, 1)
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, digitsPanelLayout.createSequentialGroup()
                                                                .addComponent(buttonLn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(1, 1, 1)
                                                                .addComponent(buttonMc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, digitsPanelLayout.createSequentialGroup()
                                                                .addComponent(buttonTg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(1, 1, 1)
                                                                .addComponent(buttonMPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, digitsPanelLayout.createSequentialGroup()
                                                                .addComponent(buttonAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(1, 1, 1)
                                                                .addComponent(buttonMMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(buttonBktClose, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(1, 1, 1)
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(buttonDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(buttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonOneDivX, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(1, 1, 1)
                                                                .addComponent(buttonMr, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 0, 0))
        );
        digitsPanelLayout.setVerticalGroup(
                digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(buttonInterest, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(buttonSw, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(buttonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(buttonBktClose, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(buttonRoot, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(buttonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(buttonBktOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(1, 1, 1)
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonExp, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonOneDivX, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonMr, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(buttonPow, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(1, 1, 1)
                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonSub, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(1, 1, 1)
                                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(1, 1, 1)
                                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonzap, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(digitsPanelLayout.createSequentialGroup()
                                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(buttonMc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonPi, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonLog, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonLn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(1, 1, 1)
                                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(buttonMPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonSin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonCos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonTg, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(1, 1, 1)
                                                                .addGroup(digitsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(buttonMMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonAsin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonAcos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(buttonAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addComponent(separatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(digitsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gradientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(gradientPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(digitsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
        );

        pack();
    }

}
